### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Roker2** [gukihuman/spirit-of-lira#1]
![image](https://github.com/gukihuman/spirit-of-lira/assets/25015209/6a17934c-9c26-4a5a-a476-637f8fc60c9d)

P. S. Рад видеть, что все еще программируешь, Иван :)

**Comment by ae8sea5af9ws** [comment]
> ![image](https://user-images.githubusercontent.com/25015209/258363590-6a17934c-9c26-4a5a-a476-637f8fc60c9d.png)
> 
> P. S. Рад видеть, что все еще программируешь, Иван :)

Спасибо! Это мелкая ошибка я сегодня же поправлю. Пока еще не было никакого релиза поэтому у меня вся разработка в основной ветке и такие ошибки могут еще быть. Когда будет готова первая демка и я начну публично ее продвигать, разработка уже будет в отдельной ветке, пока так удобнее.

P.S. На эту игру большие планы у меня :)
